encrypted_name = None
char_to_replace = {"'": "A",
                   "1": "B",
                   "q": "C",
                   "a": "D",
                   "z": "E",
                   "w": "F",
                   "s": "G",
                   "x": "H",
                   "3": "I",
                   "e": "J",
                   "d": "K",
                   "c": "L",
                   "4": "M",
                   "r": "N",
                   "f": "O",
                   "v": "P",
                   "5": "Q",
                   "t": "R",
                   "g": "S",
                   "b": "T",
                   "6": "U",
                   "y": "V",
                   "h": "W",
                   "n": "X",
                   "7": "Y",
                   "u": "Z",
                   ".": "a",
                   "0": "b",
                   "p": "c",
                   "ç": "d",
                   ";": "e",
                   "-": "f",
                   "´": "g",
                   "~": "h",
                   "/": "i",
                   "=": "j",
                   "[": "k",
                   "]": "l",
                   "?": "m",
                   "}": "n",
                   "{": "o",
                   ":": "p",
                   "^": "q",
                   "`": "r",
                   ">": "s",
                   "<": "t",
                   "!": "u",
                   "@": "v",
                   "#": "w",
                   "$": "x",
                   "%": "y",
                   "¨": "z",
                   "l": "1",
                   "j": "2",
                   "m": "3",
                   "8": "4",
                   "i": "5",
                   "k": "6",
                   ",": "7",
                   "9": "8",
                   "o": "9"}


def decrypt():
    global encrypted_name
    encrypted_name = input("Enter your encrypted name: ")
    encrypted_name = encrypted_name.translate(str.maketrans(char_to_replace))
    print("Your decrypted name: " + encrypted_name)
    return encrypted_name
