name = None
char_to_replace = {"A": "'",
                   "B": "1",
                   "C": "q",
                   "D": "a",
                   "E": "z",
                   "F": "w",
                   "G": "s",
                   "H": "x",
                   "I": "3",
                   "J": "e",
                   "K": "d",
                   "L": "c",
                   "M": "4",
                   "N": "r",
                   "O": "f",
                   "P": "v",
                   "Q": "5",
                   "R": "t",
                   "S": "g",
                   "T": "b",
                   "U": "6",
                   "V": "y",
                   "W": "h",
                   "X": "n",
                   "Y": "7",
                   "Z": "u",
                   "a": ".",
                   "b": "0",
                   "c": "p",
                   "d": "ç",
                   "e": ";",
                   "f": "-",
                   "g": "´",
                   "h": "~",
                   "i": "/",
                   "j": "=",
                   "k": "[",
                   "l": "]",
                   "m": "?",
                   "n": "}",
                   "o": "{",
                   "p": ":",
                   "q": "^",
                   "r": "`",
                   "s": ">",
                   "t": "<",
                   "u": "!",
                   "v": "@",
                   "w": "#",
                   "x": "$",
                   "y": "%",
                   "z": "¨",
                   "1": "l",
                   "2": "j",
                   "3": "m",
                   "4": "8",
                   "5": "i",
                   "6": "k",
                   "7": ",",
                   "8": "9",
                   "9": "o"}


def encrypt():
    global name
    name = input("Let's start..." + "\n" + "What's your name? ")
    name = name.translate(str.maketrans(char_to_replace))
    print("Your encrypted name: " + name)
    return name
